import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import PersonDetails from "./components/PersonDetails";
import PersonSearch from "./components/PersonSearch";
import RelationshipInspector from "./components/RelationshipInspector";
const panelClass = "rounded-3xl border border-white/10 bg-slate-900/60 p-6 shadow-2xl shadow-black/40 backdrop-blur";
export default function App() {
    const [selectedPersonId, setSelectedPersonId] = useState(null);
    return (_jsxs("div", { className: "relative isolate min-h-screen bg-slate-950 text-slate-100", children: [_jsxs("div", { className: "pointer-events-none absolute inset-0 -z-10 overflow-hidden", "aria-hidden": "true", children: [_jsx("div", { className: "absolute -left-48 top-0 h-80 w-80 rounded-full bg-indigo-600/40 blur-[160px]" }), _jsx("div", { className: "absolute -right-32 top-40 h-96 w-96 rounded-full bg-fuchsia-600/30 blur-[180px]" })] }), _jsxs("div", { className: "mx-auto flex w-full max-w-6xl flex-col gap-10 px-4 py-12 lg:px-6 lg:py-16", children: [_jsxs("header", { className: "space-y-4", children: [_jsx("span", { className: "inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-4 py-1 text-xs font-semibold uppercase tracking-[0.3em] text-indigo-200", children: "alpha build" }), _jsxs("div", { className: "space-y-3", children: [_jsx("h1", { className: "text-3xl font-semibold text-white sm:text-4xl", children: "Roglo Admin Portal" }), _jsx("p", { className: "max-w-3xl text-base leading-relaxed text-slate-300", children: "Explore les personnes expos\u00E9es par l'API GraphQL, v\u00E9rifie leur confidentialit\u00E9 et simule les liens de parent\u00E9. Tout est pr\u00EAt pour que Lovable puisse construire un aper\u00E7u sans erreur." })] })] }), _jsxs("main", { className: "grid gap-6 lg:grid-cols-[360px,1fr]", children: [_jsx("section", { className: panelClass, children: _jsx(PersonSearch, { selectedPersonId: selectedPersonId, onSelect: setSelectedPersonId }) }), _jsxs("section", { className: "flex flex-col gap-6", children: [_jsx("div", { className: panelClass, children: _jsx(PersonDetails, { personId: selectedPersonId }) }), _jsx("div", { className: "rounded-3xl border border-indigo-500/30 bg-indigo-500/10 p-6 shadow-2xl shadow-indigo-900/30 backdrop-blur", children: _jsx(RelationshipInspector, { basePersonId: selectedPersonId }) })] })] })] })] }));
}
